"""initial schema — events, materials, sponsors, notifications

Revision ID: 5b0139a03348
Revises:
Create Date: 2026-04-29 16:45:36.868999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0139a03348'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_category = sa.Enum(
        'ACADEMIC',
        'SPORT',
        'CAREER',
        'VOLUNTEER',
        'CULTURAL',
        name='eventcategory',
    )
    participation_mode = sa.Enum(
        'PHYSICAL',
        'ONLINE',
        'HYBRID',
        name='participationmode',
    )
    file_type = sa.Enum(
        'PDF',
        'IMAGE',
        'PRESENTATION',
        name='filetype',
    )
    notification_type = sa.Enum(
        'REMINDER',
        'CONFIRMATION',
        'CANCELLATION',
        name='notificationtype',
    )

    op.create_table(
        'events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('category', event_category, nullable=True),
        sa.Column('participation_mode', participation_mode, nullable=True),
        sa.Column('capacity', sa.Integer(), nullable=True),
        sa.Column('qr_code', sa.String(length=500), nullable=True),
        sa.Column('link_registration', sa.String(length=500), nullable=True),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column('organizer_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_events_organizer_id'),
            ['organizer_id'],
            unique=False,
        )

    op.create_table(
        'materials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_type', file_type, nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['events.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_materials_event_id'),
            ['event_id'],
            unique=False,
        )

    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=True),
        sa.Column('type', notification_type, nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['events.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_notifications_event_id'),
            ['event_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_notifications_user_id'),
            ['user_id'],
            unique=False,
        )

    op.create_table(
        'sponsors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('logo_url', sa.String(length=500), nullable=True),
        sa.Column('website_url', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['events.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_sponsors_event_id'),
            ['event_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_event_id'))
    op.drop_table('sponsors')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_event_id'))
    op.drop_table('notifications')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_event_id'))
    op.drop_table('materials')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_organizer_id'))
    op.drop_table('events')
    # ### end Alembic commands ###
